version: "3.8"
services:
  
  app:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
    - .:/app
    ports:
    - 8000:8000
    depends_on:
      mysql:
        condition: service_healthy

  migrate:
    init: true
    build:
      context: .
      dockerfile: dockerfile
    command: python manage.py migrate 
    volumes:
    - .:/app
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:latest
    ports:
    - 3306:3006
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test_db
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
